### ISSUE TITLE
Freckle renamed to nokotime.com

### ISSUE THREAD

**Issue by Seldaek** [RobertDaleSmith/noko-chrome-extension#7]
The extension stopped working as the domain is not whitelisted. Any chance of releasing a fix?

**Comment by RobertDaleSmith** [comment]
Thanks for heads up @Seldaek! I'll try to jump on this as soon as I get a chance. Feel free to open a PR if you can get to it before me.

**Comment by RobertDaleSmith** [comment]
This should be resolved now. Try reinstalling: https://chrome.google.com/webstore/detail/noko-timer-unofficial-ext/ioekbdkfnchkpeopaeboihedihfjcdag/

**Comment by Seldaek** [comment]
Thanks. Works like a charm once more :)
